import type { Metadata } from "next";
import { ThemeProvider } from "./components/ThemeProvider";

//your meta data title can have a default value , absolute and temolates.
//check serveraction note tis is code example that uses theme.

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next js Tutorial ",
    template: "%s | manasseh site",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
//check out the client route on how we are using the theme
