import type { Metadata } from 'next'

//your meta data title can have a default value , absolute and temolates.

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next js Tutorial ",
    template: "%s | manasseh site",
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
